import type { Metadata } from "next";

/*Site-wide SEO configuration
   The canonical origin of the site — this is what every canonical tag,
   the sitemap, structured data and Open Graph URL resolve to.

   Pick ONE host and stick to it (currently the www host). The other host
   should 301-redirect here, so search engines never see duplicate sites.
   Override with NEXT_PUBLIC_SITE_URL if the domain ever changes. */

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://www.nayadiganta.club"
).replace(/\/+$/, "");


/* Backend REST API (used for server-side metadata + sitemap generation). */
export const API_URL = (
  process.env.NEXT_PUBLIC_API_URL || "https://football-club-997m.onrender.com/api"
).replace(/\/+$/, "");

/* ─── Club identity ─── */
export const SITE_NAME = "Nayadiganta Sporting Club";
export const SITE_SHORT_NAME = "Nayadiganta SC";
export const SITE_LOCALE = "en_US";
export const SITE_LANGUAGE = "en";

export const CLUB = {
  name: SITE_NAME,
  legalName: "Nayadiganta Sporting Club",
  founded: "2025",
  /** Street / area line. */
  address: "Bhuiyyarhat Chowrasta",
  city: "Kabirhat",
  region: "Noakhali",
  country: "Bangladesh",
  countryCode: "BD",
  sport: "Association football",
  logo: "https://res.cloudinary.com/xjrgjslb/image/upload/v1788376645/fclub/1788376643695-77153592.jpg",
  /* Add real profile URLs here (Facebook / Instagram / YouTube / X) — they power
     the "sameAs" structured-data property that search engines use to verify the club. */
  socials: [] as string[],
} as const;

export const DEFAULT_TITLE = `${SITE_NAME} — Official Football Club Website`;
export const DEFAULT_SHORT_TITLE = `${SITE_SHORT_NAME} | Football Club`;

export const DEFAULT_DESCRIPTION =
  "The official website of Nayadiganta Sporting Club — a football club founded in 2025 at Bhuiyyarhat Chowrasta, Kabirhat, Noakhali, Bangladesh. Squad profiles, fixtures, live scores, results, league standings, news, gallery and youth academy.";

export const DEFAULT_KEYWORDS = [
  "Nayadiganta Sporting Club",
  "Nayadiganta SC",
  "Nayadiganta football club",
  "Kabirhat football club",
  "Bhuiyyarhat Chowrasta",
  "Bhuiyyarhat football club",
  "Noakhali football",
  "Bangladesh football club",
  "football club Bangladesh",
  "club fixtures and results",
  "football squad profiles",
  "youth football academy Bangladesh",
  "live football scores",
  "league standings",
];

/* Absolute default social-share image (generated by src/app/opengraph-image.tsx). */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`;

export const absoluteUrl = (path = "/") =>
  `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;

/* Page metadata builder*/

export type PageMeta = {
  /** Page title. The root layout appends " | Nayadiganta Sporting Club". */
  title: string;
  description: string;
  /** Route path, e.g. "/squad" — also used as the canonical URL. */
  path: string;
  keywords?: string[];
  /** Absolute URLs of share images. Falls back to the generated OG card. */
  images?: (string | undefined | null)[];
  type?: "website" | "article" | "profile";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  /** Set true for pages that must never appear in search results. */
  noindex?: boolean;
};

export function buildMetadata(meta: PageMeta): Metadata {
  /* The root layout's title.template is not inherited by dynamically rendered
     routes (generateMetadata in a dynamic segment), so the brand suffix is
     applied here explicitly. An absolute title bypasses the template, which
     keeps the result identical on static and dynamic pages. */
  const fullTitle = `${meta.title} | ${SITE_NAME}`;
  const images = (meta.images || []).filter((src): src is string => Boolean(src));
  // Always emit a share image: a child route's openGraph object replaces the
  // parent's entirely, so without an explicit fallback the generated OG card
  // from the root layout would be dropped on every nested page.
  const ogImages = images.length > 0 ? images : [DEFAULT_OG_IMAGE];

  return {
    title: { absolute: fullTitle },
    description: meta.description,
    keywords: meta.keywords,
    alternates: { canonical: meta.path },
    robots: meta.noindex
      ? { index: false, follow: false }
      : { index: true, follow: true },
    openGraph: {
      type: meta.type ?? "website",
      url: meta.path,
      siteName: SITE_NAME,
      locale: SITE_LOCALE,
      title: meta.title,
      description: meta.description,
      images: ogImages,
      ...(meta.publishedTime ? { publishedTime: meta.publishedTime } : {}),
      ...(meta.modifiedTime ? { modifiedTime: meta.modifiedTime } : {}),
      ...(meta.authors && meta.authors.length > 0 ? { authors: meta.authors } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: meta.title,
      description: meta.description,
      images: ogImages,
    },
  };
}

/*   Server-side data fetching (metadata, sitemap, structured data)
   Never throws: a cold or unreachable API degrades to the fallback so a
   build or a page render can always complete. */

export async function serverFetch<T = any>(
  path: string,
  revalidate = 3600,
): Promise<T | null> {
  try {
    const res = await fetch(`${API_URL}${path}`, {
      next: { revalidate },
      headers: { Accept: "application/json" },
      /* Generous timeout: serverFetch also runs at build time, where a cold
         API instance can take several seconds to wake. A short timeout here
         means pages get prerendered with empty content. */
      signal: AbortSignal.timeout(20000),
    });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

/** Collapse whitespace + strip markdown/HTML noise, then clip to a meta-friendly length. */
export function metaDescription(raw: string | undefined | null, fallback: string, max = 160): string {
  if (!raw) return fallback;
  const clean = raw
    .replace(/<[^>]*>/g, " ")
    .replace(/[#*_>`~\[\]()]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (!clean) return fallback;
  if (clean.length <= max) return clean;
  return `${clean.slice(0, max - 1).trimEnd()}…`;
}

export function truncate(raw: string | undefined | null, max = 70): string {
  if (!raw) return "";
  const clean = raw.replace(/\s+/g, " ").trim();
  return clean.length <= max ? clean : `${clean.slice(0, max - 1).trimEnd()}…`;
}
